/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Algorithms.Algorithm;
import graphalgorithms.GraphTools;
/**
 *
 * @author Student
 */
public class GraphAlgPanel extends GraphPanel {
    
    private Algorithm alg;
    
    public GraphAlgPanel(Algorithm alg) {
        initComponents();
        this.alg = alg;
        menuButton.setEnabled(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        skipDemoButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JToggleButton();
        menuButton = new javax.swing.JButton();

        skipDemoButton.setText("Skip To End");
        skipDemoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipDemoButtonActionPerformed(evt);
            }
        });

        pauseButton.setText("Pause");
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });

        menuButton.setText("Back To Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(pauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(menuButton)
                .addGap(58, 58, 58)
                .addComponent(skipDemoButton)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(547, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skipDemoButton)
                    .addComponent(pauseButton)
                    .addComponent(menuButton))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void skipDemoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipDemoButtonActionPerformed
        alg.setSpeed(0);
    }//GEN-LAST:event_skipDemoButtonActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        if(alg.getPauseStatus() == false){
            alg.setPause(true);
        } else {
            synchronized (alg){
                try{
                    alg.notifyAll();
                } catch(Exception ex){}
            }
            alg.setPause(false);
        }
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        GraphTools.getFrame().setPanel(this, new StartPanel());
    }//GEN-LAST:event_menuButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton menuButton;
    private javax.swing.JToggleButton pauseButton;
    private javax.swing.JButton skipDemoButton;
    // End of variables declaration//GEN-END:variables

public void finish(){
    menuButton.setEnabled(true);
}

}
