/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Algorithms.*;
import GraphPackage.*;
import graphalgorithms.GraphTools;

/**
 *
 * @author Student
 */
public class StartPanel extends javax.swing.JPanel {

    /**
     * Creates new form StartPanel
     */
    public StartPanel() {
        initComponents();
        openFileButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openFileButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        demoButton = new javax.swing.JButton();
        testButton = new javax.swing.JButton();

        openFileButton.setText("Open from file");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(228, 228, 228));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("This software demonstrates graph theory algorithms;\nin particular, the Auslander-Parter algorithm.\nPlease open a graph from file, draw your own or use\na pre-drawn graph.");
        jScrollPane2.setViewportView(jTextArea1);

        jButton2.setText("Draw graph");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        demoButton.setText("Select demo graph");
        demoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demoButtonActionPerformed(evt);
            }
        });

        testButton.setText("Quick Test");
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(openFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(demoButton)))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(testButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openFileButton)
                    .addComponent(jButton2)
                    .addComponent(demoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addComponent(testButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //DRAW OWN GRAPH OPTION
        
        GraphTools.getFrame().setPanel(this, new GraphDrawPanel());
        if(GraphTools.getGraph() != null){
            GraphTools.drawGraph(GraphTools.getGraph());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void demoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demoButtonActionPerformed
        GraphTools.getFrame().setPanel(this, new DemoSelectPanel());
    }//GEN-LAST:event_demoButtonActionPerformed

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed
        
        Vertex v1 = new Vertex(278,172);   //top vertex
        Vertex v2 = new Vertex(202,236);   //traversing anti clockwise around outer-most cycle
        Vertex v3 = new Vertex(243,341);
        Vertex v4 = new Vertex(334,340);
        Vertex v5 = new Vertex(359,232);
        Vertex v6 = new Vertex(280,234);   //top vertex of middle trio
        Vertex v7 = new Vertex(256,274);   //bottom left of trio
        Vertex v8 = new Vertex(305,273);   //bottom right of trio
        
        Edge e1 = new Edge(v1,v2);  //cycle edges
        Edge e2 = new Edge(v2,v3);
        Edge e3 = new Edge(v3,v4);
        Edge e4 = new Edge(v4,v5);
        Edge e5 = new Edge(v5,v1);
        
        Edge e11 = new Edge(v6,v1);  //Segment 2 edges
        Edge e12 = new Edge(v6,v2);
        Edge e13 = new Edge(v6,v5);
        
        Edge e21 = new Edge(v7,v3);  //segment 1 edges
        Edge e22 = new Edge(v7,v4);
        Edge e23 = new Edge(v7,v5);
        
        Edge e31 = new Edge(v8,v1);  //segment 3 edges
        Edge e32 = new Edge(v8,v2);
        Edge e33 = new Edge(v8,v4);
        
        Graph H = new Graph();
        
        H.addVertex(v1);
        H.addVertex(v2);
        H.addVertex(v3);
        H.addVertex(v4);
        H.addVertex(v5);
        H.addVertex(v7); //last 3 entered in irregular order to agree with dissertation segment numberings
        H.addVertex(v6);
        H.addVertex(v8);
        
        H.addEdge(e1);
        H.addEdge(e2);
        H.addEdge(e3);
        H.addEdge(e4);
        H.addEdge(e5);
        
        H.addEdge(e11);
        H.addEdge(e12);
        H.addEdge(e13);
        
        H.addEdge(e21);
        H.addEdge(e22);
        H.addEdge(e23);
        
        H.addEdge(e31);
        H.addEdge(e32);
        H.addEdge(e33);
        
        GraphTools.setGraph(H);
        
        Algorithm alg = new AuslanderParter(250);
        
        alg.setStartVertex(GraphTools.getGraph().getVertex(0));
        Thread t = new Thread(alg);
        GraphTools.getFrame().setPanel(this, new GraphAlgPanel(alg));
        GraphTools.drawGraph(GraphTools.getGraph());
        t.start();
        
    }//GEN-LAST:event_testButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton demoButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton openFileButton;
    private javax.swing.JButton testButton;
    // End of variables declaration//GEN-END:variables

//    private static final int DEFAULT_WIDTH = 600;
//    private static final int DEFAULT_HEIGHT = 600;
//    public Dimension getPreferredSize() {return new Dimension(DEFAULT_WIDTH, DEFAULT_HEIGHT); }

}
